--===================
-- PostgreSQL IS NULL
--===================

-- The comparison of NULL with a value will always result in NULL, which means an unknown result.
-- In addition, NULL is not equal to NULL so the following expression returns NULL:
--      NULL = NULL

CREATE TABLE contacts(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(15),
    PRIMARY KEY (id)
);

INSERT INTO contacts(first_name, last_name, email, phone)
VALUES ('John','Doe','john.doe@example.com',NULL),
    ('Lily','Bush','lily.bush@example.com','(408-234-2764)');


SELECT
    id,
    first_name,
    last_name,
    email,
    phone
FROM
    contacts
WHERE
    phone = NULL;   -- The statement returns no row. This is because the expression phone = NULL in the WHERE clause
                    -- always returns false.

-- To get the contact who does not have any phone number stored in the phone column, you use the following statement
-- instead:
SELECT
    id,
    first_name,
    last_name,
    email,
    phone
FROM
    contacts
WHERE
    phone IS NULL;


-- To find the contact who does have a phone number, you use the following statement:
SELECT
    id,
    first_name,
    last_name,
    email,
    phone
FROM
    contacts
WHERE
    phone IS NOT NULL;

