# This uses postgres/example as the user/password credentials
# To fire it up, use the command: docker-compose -f docker-compose.yml up
version: '3.1'

services:

  db:
    image: postgres:12
    container_name: postgrestutorial
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

#  adminer:
#    image: adminer
#    container_name: adminer
#    restart: always
#    ports:
#      - 8080:8080