FROM postgis/postgis:13-master

SHELL ["/bin/bash", "-c"]

#WORKDIR /app

#COPY . /app/

#RUN chmod +x docker-entrypoint.sh
#RUN ./docker-entrypoint.sh

# ENTRYPOINT uname -a

#RUN PGPASSWORD=example psql --username=postgres --no-password --host=localhost -c "DROP DATABASE IF EXISTS $db_name;"
# RUN PGPASSWORD=example psql --username=postgres --no-password --host=localhost -c "DROP USER IF EXISTS $db_user;"

# RUN PGPASSWORD=example psql --username=postgres --no-password --host=localhost -c "CREATE DATABASE $db_name;"
# RUN PGPASSWORD=example psql --username=postgres --no-password --host=localhost -c "CREATE USER $db_user WITH ENCRYPTED PASSWORD '$db_pass';"
# RUN PGPASSWORD=example psql --username=postgres --no-password --host=localhost -c "GRANT ALL PRIVILEGES ON DATABASE $db_name TO $db_user;"

#ENTRYPOINT ["docker-entrypoint.sh"]

#CMD tail -F /dev/null
