# This uses mysql/example as the user/password credentials
# To fire it up, use the command: docker-compose -f docker-compose.yml up
version: '3.1'

services:

  db:
    image: mysql:8
    container_name: mysqltutorial
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080